on:
  push:
    branches:
      #      - 'main'
      - 'misc'
  pull_request:
    branches:
      #      - 'main'
      - 'misc'

jobs:
  build:
    if: github.repository == 'nevmock/LaporAA-Executive-FE'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    - name: Load variables
      run: |
        touch .env
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build

  deploy:
    if: github.repository == 'nevmock/LaporAA-Executive-FE' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd ${{ secrets.PATH }}
            git reset --hard HEAD
            git pull origin main --rebase
            npm install
            npm run build
            docker compose down
            docker compose up -d --build
            docker system prune -f
